server:
  port: 8090
  forward-headers-strategy: framework

spring:
  application:
    name: ApiGateway
  cloud:
    consul:
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bureaucracy-service
          uri: lb://bureaucracyService
          predicates:
            - Path=/bureaucracy/**
          filters:
            - RewritePath=/bureaucracy/(?<path>.*), /$\{path}

        - id: medical-service
          uri: lb://medicalService
          predicates:
            - Path=/med/**
          filters:
            - RewritePath=/med/(?<path>.*), /$\{path}

        - id: qr-management
          uri: lb://qrManagementService
          predicates:
            - Path=/qr/**
          filters:
            - RewritePath=/qr/(?<path>.*), /$\{path}

        - id: auth-service
          uri: lb://AuthService
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}


springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: bureaucracy-service
      paths-to-match:
        - /bureaucracy/**
      display-name: BureaucracyService

    - group: medical-service
      paths-to-match:
        - /med/**
      display-name: MedicalService

    - group: qr-management
      paths-to-match:
        - /qr/**
      display-name: QRManagement

    - group: auth-service
      paths-to-match:
        - /auth/**
      display-name: AuthService

  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /bureaucracy/v3/api-docs
        name: BureaucracyService
      - url: /med/v3/api-docs
        name: MedicalService
      - url: /qr/v3/api-docs
        name: QRManagement
      - url: /auth/v3/api-docs
        name: AuthService